RelationTypes/One To many/Strong/objects/College__c.object
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RelationTypes/Self/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employees (Employee)</relationshipLabel>
        <relationshipName>Employees1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RelationTypes/One to One/objects/Pan_Card__c.object
<CustomObject>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pan_Number__c</fullName>
        <label>Pan Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Pan Card</label>
    <nameField>
        <label>Pan Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pan Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RelationTypes/Many To Many/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <recordTypes>
        <fullName>Teacher</fullName>
        <active>true</active>
        <label>Teacher</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RelationTypes/Many To Many/objects/Subject__c.object
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RelationTypes/One To many/Strong/objects/Teacher__c.object
<CustomObject>
    <fields>
        <fullName>College__c</fullName>
        <label>College</label>
        <referenceTo>College__c</referenceTo>
        <relationshipLabel>Teachers</relationshipLabel>
        <relationshipName>Teachers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RelationTypes/One To many/Weak/objects/Year_of_Class__c.object
<CustomObject>
    <label>Year of Class</label>
    <nameField>
        <label>Year of Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years of Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RelationTypes/Apex Class/classes/RelationTypes.cls
/**
                    * Description   - This is a class of all relation types i.e. one to one,one to many, many to many, self relation and Hierarchical relations by using lookup and master-detail fields.
                    *
                    * Created by    - Prateek Bhadoria
                    *
                    * Created Date  - 15/06/2022
                    *
                    * Revision log  -  V_1.0 - Created  - Your name -Prateek Bhadoria, Date- 15/06/2022
                    *
                    **/
                    public class RelationTypes {
                    /**   Description :   To insert Pancard, One to One Realtionship(Lookup Relatioship)
                    *
                    *     Created By  :   Prateek Bhadoria
                    *
                    *     Arguments   :   
                    *
                    *     Return      :   Void
                    *
                    *     Revision log:   V_1.0 - Created  - Your name - Prateek Bhadoria, Date- 15/06/2022
                    * 
                    **/
                    public static void insertPanCard(){
                    Pan_Card__c pancard = new Pan_Card__c();
                    pancard.Name = 'Prateek Bhadoria';
                    pancard.Pan_Number__c = 'EAJPB9511C';
                    pancard.Father_Name__c = 'Vimlesh Singh Bhadoria';
                    
                    insert pancard;
                    system.debug('Inserted PanCard Data :' + pancard.id);
                    
                     //Weak Realtionship
                    //Year of Class Info
                    Year_Of_Class__c yearofclass = new Year_Of_Class__c();
                    yearofclass.Name = '3rd Year';
                    
                    insert yearofclass;
                    system.debug('Inserted Year Of Class  :' + yearofclass.id);
                    
                    // ContactInfo
                    Contact contact = new Contact();
                    contact.Pan_Card__c = pancard.Id;
                    contact.FirstName = 'Prateek';
                    contact.LastName = 'Bhadoria';
                    contact.MobilePhone = '9588977678';
                    contact.Languages__c = 'English';
                    contact.Year_of_Class__c = yearofclass.Id;
                   
                    insert contact;
                    system.debug('Inserted Contact Data :' + contact.id);
                    
                    }
                    /**   Description :   To insert College info, one to many (Strong relationship)
                    *
                    *     Created By  :   Prateek Bhadoria
                    *
                    *     Arguments   :   
                    *
                    *     Return      :   Void
                    *
                    *     Revision log:   V_1.0 - Created  - Your name - Prateek Bhadoria, Date- 15/06/2022
                    * 
                    **/
                    public static void insertCollegeInfo(){
                    College__c college = new College__c();
                    college.Name = 'Jagannath Gupta Institute of Engineering and Technology';
                    
                    insert college;
                    system.debug('Inserted  College Info :' + college.id);
                    
                    //Teacher Info
                    Teacher__c teacher = new Teacher__c();
                    teacher.Name = 'Y C Bhatt';
                    teacher.College__c = college.Id;
                    
                    insert teacher;
                    system.debug('Inserted Teacher Info :' + teacher.id);
                   
                    //Student Info
                    Student__c student = new Student__c();
                    student.Name = 'Prateek Bhadoria';
                    
                    insert student;
                    system.debug('Inserted Student Info  :' + student.id);
                   
                    //Many to Many Realtionship
                    //Subject Info
                    Subject__c subject = new Subject__c();
                    subject.Name = 'Physics';
                    
                    insert subject;
                    system.debug('Inseted Subject Info :' + subject.id);
                    
                    //StudentSubjects Info 
                    StudentSubject__c stusubs = new StudentSubject__c();
                    stusubs.Name = 'PHY007';
                    stusubs.Student__c = student.Id;
                    stusubs.Subject__c = subject.Id;
                    
                    insert stusubs;
                    system.debug('Inseted StudentSubjects Info :' + stusubs.id);
                    }
                    /**   Description :   To insert Hierarchical data
                    *
                    *     Created By  :   Prateek Bhadoria
                    *
                    *     Arguments   :   
                    *
                    *     Return      :   Void
                    *
                    *     Revision log:   V_1.0 - Created  - Your name - Prateek Bhadoria, Date- 15/06/2022
                    * 
                    **/
                    public static void insertHierarchical(){    
                    //Account Hierarchy RelationType
                    //Employees Info
                    
                    Contact contact = [SELECT Id FROM Contact WHERE Name Like 'Prateek Bhadoria' Limit 1];
                    Account accId = [SELECT Id,ParentId FROM Account WHERE Name Like 'General Electric New York US' LIMIT 1];
                    Employee__c employee = [SELECT Mentor__c,Trainer__c FROM Employee__c WHERE Name LIKE 'Sushil Choudhary' LIMIT 1];
                    
                    Employee__c empl = new Employee__c();
                    empl.Name = 'Sagar Nirwal';
                    empl.Mentor__c = employee.Id ;
                    empl.Trainer__c = employee.Mentor__c ;
                    
                    insert empl;
                    system.debug('Inserted Employees Info :' + empl.id);
                    
                    //Account Info
                    
                    Account account = new Account();
                    account.Name = 'GE India';
                    account.ParentId = accId.ParentId;
                        
                    insert account;
                    system.debug('Inseted Employees Info :' + account.id);
                    
                    //Leads Info
                    Lead lead = new Lead();
                    lead.FirstName = 'Prateek';
                    lead.LastName = 'Bhadoria';
                    lead.Company = 'Fexle Services Private Limited';
                    lead.LeadSource = 'Phone';
                    lead.Industry = 'IT Industry';
                    lead.AnnualRevenue = 1000000;
                    lead.Phone = '+919588977678';
                    lead.Email = 'prateek.bhadoria@fexle.com';
                    lead.Status = 'Working - Contacted';
                    lead.Rating = 'Warm';
                    
                    insert lead;
                    system.debug('Inseted Lead Info :' + lead.id);
                    
                    //One Contact Headquarter account Update
                    Contact con = new Contact();
                    con.Id = contact.Id;
                    con.AccountId = accId.Id;
                    
                    update con;
                    system.debug('Update Contact :' + con.id);      
                }   
            
            }