RelationTypes/Many To Many/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <label>Pending Fees Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B.Arch</fullName>
                </value>
                <value>
                    <fullName>B.Com</fullName>
                </value>
                <value>
                    <fullName>B.Tech</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BCA</fullName>
                </value>
                <value>
                    <fullName>M.Tech</fullName>
                </value>
                <value>
                    <fullName>MBA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Email_Id__c</fullName>
        <label>Student Email Id</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <recordTypes>
        <fullName>Registrar</fullName>
        <active>true</active>
        <label>Registrar</label>
    </recordTypes>
    <recordTypes>
        <fullName>Teacher</fullName>
        <active>true</active>
        <label>Teacher</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StudentData/classes/StudentData.cls
/**
* Description   - This is a class of student record of college for teacher and registrar.
*
* Created by    - Prateek Bhadoria
*
* Created Date  - 08/06/2022
*
* Revision log  -  V_1.0 - Created  - Youe name -Prateek Bhadoria, Date- 15/10/2022
*
**/
public class StudentData {
   
    /**   Description :   To insert student's records
    *
    *     Created By  :   Prateek Bhadoria
    *
    *     Arguments   :   
    *
    *     Return      :   Void
    *
    *     Revision log:   V_1.0 - Created  - Youe name - Prateek Bhadoria, Date- 15/10/2022
    * 
    **/
    public StudentData(){
        
        //Insert Student Record
        Student__c s1 = new Student__c();
        s1.Name = 'ABC';
        //Insert Student Record in Teacher Layout
        Id recordTypeIdOfStudent = Schema.SObjectType.Student__c.getRecordTypeInfosByName().get('Teacher').getRecordTypeId();
        s1.RecordTypeId = recordTypeIdOfStudent;
        s1.Roll_Number__c = 2345;
        s1.Address__c = 'Alwar';
        s1.Student_Email_Id__c = 'xyz@fexle.com';
        s1.Overall_Grade__c = 75;
        s1.Stream__c = 'M.Tech';
        s1.Pending_Fees_Amount__c = 100;
        insert s1;
        
        //Query 5 Students
        for(Student__c student : [select id, name, Roll_Number__c from Student__c order by createdDate DESC LIMIT 5])
            system.debug('Check Student Data ::: ' + student);
    }
}